on:
  workflow_run:
    workflows: ['Deploy']
    types:
      - completed

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    working-directory: ./deploy
    steps:
      - name: apply
        run: terraform apply -auto-approve -input=yes